# Generated by Django 5.0.6 on 2024-06-28 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='cast',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='cast',
            name='contactInfo',
        ),
        migrations.RemoveField(
            model_name='cast',
            name='name',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='age',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='contactInfo',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='name',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='nationality',
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cast', models.ManyToManyField(related_name='projects_for_cast', to='crewManagement.cast')),
                ('crew', models.ManyToManyField(related_name='projects_for_crew', to='crewManagement.crew')),
            ],
        ),
        migrations.AddField(
            model_name='cast',
            name='projects',
            field=models.ManyToManyField(related_name='cast_members', to='crewManagement.project'),
        ),
        migrations.AddField(
            model_name='crew',
            name='projects',
            field=models.ManyToManyField(related_name='crew_members', to='crewManagement.project'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('availability', models.BooleanField()),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crewManagement.contactinfo')),
            ],
        ),
        migrations.AddField(
            model_name='cast',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crewManagement.user'),
        ),
        migrations.AddField(
            model_name='crew',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crewManagement.user'),
        ),
    ]
