# Generated by Django 5.0.6 on 2024-06-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewManagement', '0002_contactinfo_remove_cast_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
